### ISSUE TITLE
WSL eror can't install 

### ISSUE THREAD

**Issue by if-ai** [NimaNzrii/comfyui-popup_preview#2]
possible problem with the preview requiremts Requirement on wsl ```
already satisfied: opencv-python==4.8.1.78 in /home/impactframes/micromamba/envs/comfy/lib/python3.10/site-packages (from -r requirements.txt (line 1)) (4.8.1.78)
ERROR: Could not find a version that satisfies the requirement pywin32==306 (from versions: none)
ERROR: No matching distribution found for pywin32==306
```

can you modify to use a wsl alternative for pywin32?

**Comment by NimaNzrii** [comment]
next versions doesn't even need popup preview

**Comment by if-ai** [comment]
Fantastic will wait for that, marvelous.
