### ISSUE TITLE
Many custom nodes broken after 89d6a97

### ISSUE THREAD

**Issue by rgthree** [NimaNzrii/comfyui-popup_preview#4]
Commit https://github.com/NimaNzrii/comfyui-popup_preview/commit/89d6a9769cd86a37bba5f49c96ef358b1deb9063 seems to break any other custom nodes that use `folder_paths` in their initialization (rgthree-comfy, ComfyUI_Comfyroll_CustomNodes, ComfyUI_tinyterraNodes, etc.).

If I had to guess, it's probably this new line:

```diff
+ os.chdir(os.path.join(node_path, "window"))
```

Which is likely changing the operating directory following nodes are using. Probably safer to avoid changing the directory, and just checking/invoking from the current path.

**Comment by NimaNzrii** [comment]
Thank you for your report. This problem should be solved now, please update the node and test it again.
If there is any problem, please report it.

**Comment by rgthree** [comment]
LGTM
